Collect event filename
yiisoft/yii-debug pull request #120
Opened 2022-03-24 15:33 UTC by rustamwin

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️/❌
| Breaks BC?    | ❌
| Fixed issues  | -

2022-03-25 13:30 UTC, vjik requested changes

2022-03-25 14:27 UTC, rustamwin commented on src/Collector/EventCollector.php
> +            'file' => (new \ReflectionClass($event))->getFileName(),
Added.

2022-03-25 14:28 UTC, vjik approved these changes

2022-03-26 17:50 UTC, xepozz approved these changes

2022-03-26 18:13 UTC, merged